# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setStyleSheet("background-color: rgb(255,252,241)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SideColum_2 = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum_2.setGeometry(QtCore.QRect(1261, 0, 20, 741))
        self.SideColum_2.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum_2.setObjectName("SideColum_2")
        self.WelcomeFrame = QtWidgets.QFrame(self.centralwidget)
        self.WelcomeFrame.setGeometry(QtCore.QRect(400, 100, 491, 151))
        self.WelcomeFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WelcomeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WelcomeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WelcomeFrame.setObjectName("WelcomeFrame")
        self.label_3 = QtWidgets.QLabel(self.WelcomeFrame)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 231, 111))
        self.label_3.setStyleSheet("font: 48pt \".AppleSystemUIFont\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(37,39,51);")
        self.label_3.setObjectName("label_3")
        self.LoginFrame = QtWidgets.QFrame(self.centralwidget)
        self.LoginFrame.setGeometry(QtCore.QRect(440, 280, 411, 121))
        self.LoginFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LoginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LoginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginFrame.setObjectName("LoginFrame")
        self.startButton = QtWidgets.QPushButton(self.LoginFrame)
        self.startButton.setGeometry(QtCore.QRect(300, 90, 101, 20))
        self.startButton.setStyleSheet("background-color: rgb(255,252,241);border-color: rgb(34, 34, 34);\n"
"color: rgb(37,39,51);\n"
"border-top-color: rgb(85, 86, 86);\n"
"selection-background-color: rgb(197, 201, 201);\n"
"")
        self.startButton.setObjectName("startButton")
        self.lineEdit = QtWidgets.QLineEdit(self.LoginFrame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 50, 321, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255,252,241);\n"
"color: rgb(115, 116, 116);\n"
"selection-color: rgb(207, 212, 212);\n"
"border-color: rgb(156, 160, 159);\n"
"border-bottom-color: rgb(159, 163, 163);")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.LoginFrame)
        self.label.setGeometry(QtCore.QRect(190, 10, 71, 21))
        self.label.setStyleSheet("font: 18pt \".AppleSystemUIFont\";\n"
"color: rgb(37,39,51)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.LoginFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.label_2.setStyleSheet("color: rgb(37,39,51)\n"
"")
        self.label_2.setObjectName("label_2")
        self.SideColum_3 = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum_3.setGeometry(QtCore.QRect(890, 90, 20, 171))
        self.SideColum_3.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum_3.setObjectName("SideColum_3")
        self.SideColum_4 = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum_4.setGeometry(QtCore.QRect(380, 90, 20, 171))
        self.SideColum_4.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum_4.setObjectName("SideColum_4")
        self.SideColum_5 = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum_5.setGeometry(QtCore.QRect(420, 240, 451, 16))
        self.SideColum_5.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum_5.setObjectName("SideColum_5")
        self.SideColum_6 = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum_6.setGeometry(QtCore.QRect(420, 90, 451, 16))
        self.SideColum_6.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum_6.setObjectName("SideColum_6")
        self.SideColum_7 = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum_7.setGeometry(QtCore.QRect(0, 0, 20, 741))
        self.SideColum_7.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum_7.setObjectName("SideColum_7")
        self.startButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.startButton_2.setGeometry(QtCore.QRect(30, 720, 41, 20))
        self.startButton_2.setStyleSheet("background-color: rgba(237, 255, 229, 242);border-color: rgb(34, 34, 34);\n"
"color: rgb(37,39,51);\n"
"border-top-color: rgb(85, 86, 86);\n"
"selection-background-color: rgb(197, 201, 201);\n"
"")
        self.startButton_2.setObjectName("startButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "WELCOME"))
        self.startButton.setText(_translate("MainWindow", "ENTER"))
        self.label.setText(_translate("MainWindow", "LOGIN: "))
        self.label_2.setText(_translate("MainWindow", "NAME:"))
        self.startButton_2.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
