# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 666)
        MainWindow.setStyleSheet("background-color: rgb(255,252,241)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(890, 170, 141, 71))
        self.startButton.setStyleSheet("background-color: rgb(111, 207, 151);border-color: rgb(34, 34, 34);")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(1050, 170, 141, 71))
        self.stopButton.setStyleSheet("background-color: rgb(235,87,87)")
        self.stopButton.setObjectName("stopButton")
        self.changeExerciseButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeExerciseButton.setGeometry(QtCore.QRect(890, 280, 141, 71))
        self.changeExerciseButton.setStyleSheet("background-color: rgb(242, 201, 76)")
        self.changeExerciseButton.setObjectName("changeExerciseButton")
        self.ExportDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExportDataButton.setGeometry(QtCore.QRect(1050, 280, 141, 71))
        self.ExportDataButton.setStyleSheet("background-color: rgb(242,153,74)")
        self.ExportDataButton.setObjectName("ExportDataButton")
        self.repBanner = QtWidgets.QTextBrowser(self.centralwidget)
        self.repBanner.setGeometry(QtCore.QRect(630, 270, 201, 91))
        self.repBanner.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.repBanner.setObjectName("repBanner")
        self.voltageBanner = QtWidgets.QTextBrowser(self.centralwidget)
        self.voltageBanner.setGeometry(QtCore.QRect(400, 270, 201, 91))
        self.voltageBanner.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.voltageBanner.setObjectName("voltageBanner")
        self.ActivityBanner = QtWidgets.QTextBrowser(self.centralwidget)
        self.ActivityBanner.setGeometry(QtCore.QRect(400, 160, 431, 101))
        self.ActivityBanner.setStyleSheet("background-color: rgb(255, 255, 255);border-color: rgb(34, 34, 34);")
        self.ActivityBanner.setObjectName("ActivityBanner")
        self.SideColum = QtWidgets.QColumnView(self.centralwidget)
        self.SideColum.setGeometry(QtCore.QRect(10, 0, 201, 641))
        self.SideColum.setStyleSheet("background-color: rgb(78, 78, 78)")
        self.SideColum.setObjectName("SideColum")
        self.overviewSide = QtWidgets.QPushButton(self.centralwidget)
        self.overviewSide.setGeometry(QtCore.QRect(10, 80, 201, 41))
        self.overviewSide.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
";")
        self.overviewSide.setObjectName("overviewSide")
        self.historySide = QtWidgets.QPushButton(self.centralwidget)
        self.historySide.setGeometry(QtCore.QRect(10, 120, 201, 41))
        self.historySide.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
";")
        self.historySide.setObjectName("historySide")
        self.goalSide = QtWidgets.QPushButton(self.centralwidget)
        self.goalSide.setGeometry(QtCore.QRect(10, 160, 201, 41))
        self.goalSide.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
";")
        self.goalSide.setObjectName("goalSide")
        self.patientSetup = QtWidgets.QPushButton(self.centralwidget)
        self.patientSetup.setGeometry(QtCore.QRect(10, 200, 201, 41))
        self.patientSetup.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
";")
        self.patientSetup.setObjectName("patientSetup")
        self.PatientBanner = QtWidgets.QTextBrowser(self.centralwidget)
        self.PatientBanner.setGeometry(QtCore.QRect(210, 0, 1061, 71))
        self.PatientBanner.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PatientBanner.setObjectName("PatientBanner")
        self.Logout = QtWidgets.QPushButton(self.centralwidget)
        self.Logout.setGeometry(QtCore.QRect(10, 600, 201, 41))
        self.Logout.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
";\n"
"border-color: rgb(34, 34, 34);")
        self.Logout.setObjectName("Logout")
        self.changePatient = QtWidgets.QPushButton(self.centralwidget)
        self.changePatient.setGeometry(QtCore.QRect(10, 560, 201, 41))
        self.changePatient.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
";")
        self.changePatient.setObjectName("changePatient")
        self.ClinicianSection = QtWidgets.QTextBrowser(self.centralwidget)
        self.ClinicianSection.setGeometry(QtCore.QRect(10, 0, 201, 71))
        self.ClinicianSection.setStyleSheet("background-color: rgba(106, 108, 108, 157); color: white;\n"
"")
        self.ClinicianSection.setObjectName("ClinicianSection")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 380, 201, 121))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.changeExerciseButton.setText(_translate("MainWindow", "Change Exercise"))
        self.ExportDataButton.setText(_translate("MainWindow", "Export Data"))
        
        self.overviewSide.setText(_translate("MainWindow", "Overview"))
        self.historySide.setText(_translate("MainWindow", "History"))
        self.goalSide.setText(_translate("MainWindow", "Goal"))
        self.patientSetup.setText(_translate("MainWindow", "Patient Setup"))

 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
