# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OverviewWindow(object):
    def __init__(self, parent=None):
        super(Ui_OverviewWindow, self).__init__(parent)

        def setupUi(self, OverViewWindow):
                OverViewWindow.setObjectName("OverViewWindow")
                OverViewWindow.resize(1280, 800)
                OverViewWindow.setStyleSheet("background-color: rgb(255,252,241)\n"
        "")
                self.centralwidget = QtWidgets.QWidget(OverViewWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.startButton = QtWidgets.QPushButton(self.centralwidget)
                self.startButton.setGeometry(QtCore.QRect(890, 170, 141, 71))
                self.startButton.setStyleSheet("background-color: rgb(111, 207, 151);border-color: rgb(34, 34, 34);")
                self.startButton.setObjectName("startButton")
                self.stopButton = QtWidgets.QPushButton(self.centralwidget)
                self.stopButton.setGeometry(QtCore.QRect(1050, 170, 141, 71))
                self.stopButton.setStyleSheet("background-color: rgb(235,87,87)")
                self.stopButton.setObjectName("stopButton")
                self.changeExerciseButton = QtWidgets.QPushButton(self.centralwidget)
                self.changeExerciseButton.setGeometry(QtCore.QRect(890, 280, 141, 71))
                self.changeExerciseButton.setStyleSheet("background-color: rgb(242, 201, 76)")
                self.changeExerciseButton.setObjectName("changeExerciseButton")
                self.ExportDataButton = QtWidgets.QPushButton(self.centralwidget)
                self.ExportDataButton.setGeometry(QtCore.QRect(1050, 280, 141, 71))
                self.ExportDataButton.setStyleSheet("background-color: rgb(242,153,74)")
                self.ExportDataButton.setObjectName("ExportDataButton")
                self.SideColum = QtWidgets.QColumnView(self.centralwidget)
                self.SideColum.setGeometry(QtCore.QRect(10, 0, 201, 741))
                self.SideColum.setStyleSheet("background-color: rgb(78, 78, 78)")
                self.SideColum.setObjectName("SideColum")
                self.overviewSide = QtWidgets.QPushButton(self.centralwidget)
                self.overviewSide.setGeometry(QtCore.QRect(10, 90, 201, 41))
                self.overviewSide.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
        ";")
                self.overviewSide.setObjectName("overviewSide")
                self.historySide = QtWidgets.QPushButton(self.centralwidget)
                self.historySide.setGeometry(QtCore.QRect(10, 130, 201, 41))
                self.historySide.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
        ";")
                self.historySide.setObjectName("historySide")
                self.goalSide = QtWidgets.QPushButton(self.centralwidget)
                self.goalSide.setGeometry(QtCore.QRect(10, 170, 201, 41))
                self.goalSide.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
        ";")
                self.goalSide.setObjectName("goalSide")
                self.patientSetup = QtWidgets.QPushButton(self.centralwidget)
                self.patientSetup.setGeometry(QtCore.QRect(10, 210, 201, 41))
                self.patientSetup.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
        ";")
                self.patientSetup.setObjectName("patientSetup")
                self.Logout = QtWidgets.QPushButton(self.centralwidget)
                self.Logout.setGeometry(QtCore.QRect(10, 680, 201, 41))
                self.Logout.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
        ";\n"
        "border-color: rgb(34, 34, 34);")
                self.Logout.setObjectName("Logout")
                self.changePatient = QtWidgets.QPushButton(self.centralwidget)
                self.changePatient.setGeometry(QtCore.QRect(10, 630, 201, 41))
                self.changePatient.setStyleSheet("background-color: rgb(78,78,78); color: white\n"
        ";")
                self.changePatient.setObjectName("changePatient")
                self.WelcomeFrame = QtWidgets.QFrame(self.centralwidget)
                self.WelcomeFrame.setGeometry(QtCore.QRect(400, 160, 431, 101))
                self.WelcomeFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.WelcomeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.WelcomeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.WelcomeFrame.setObjectName("WelcomeFrame")
                self.label_3 = QtWidgets.QLabel(self.WelcomeFrame)
                self.label_3.setGeometry(QtCore.QRect(170, 10, 101, 41))
                self.label_3.setStyleSheet("font: 24pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color: #7f7f7f")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.WelcomeFrame)
                self.label_4.setGeometry(QtCore.QRect(140, 40, 171, 41))
                self.label_4.setStyleSheet("font: 24pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color:#323232")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(220, 10, 171, 31))
                self.label_5.setStyleSheet("font: 24pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color:#323232")
                self.label_5.setObjectName("label_5")
                self.WelcomeFrame_2 = QtWidgets.QFrame(self.centralwidget)
                self.WelcomeFrame_2.setGeometry(QtCore.QRect(400, 270, 211, 91))
                self.WelcomeFrame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.WelcomeFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.WelcomeFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.WelcomeFrame_2.setObjectName("WelcomeFrame_2")
                self.label_6 = QtWidgets.QLabel(self.WelcomeFrame_2)
                self.label_6.setGeometry(QtCore.QRect(90, 10, 31, 31))
                self.label_6.setStyleSheet("font: 14pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color: #7f7f7f")
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.WelcomeFrame_2)
                self.label_7.setGeometry(QtCore.QRect(50, 40, 101, 41))
                self.label_7.setStyleSheet("font: 24pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color:#323232")
                self.label_7.setObjectName("label_7")
                self.WelcomeFrame_3 = QtWidgets.QFrame(self.centralwidget)
                self.WelcomeFrame_3.setGeometry(QtCore.QRect(620, 270, 211, 91))
                self.WelcomeFrame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.WelcomeFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.WelcomeFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.WelcomeFrame_3.setObjectName("WelcomeFrame_3")
                self.label_8 = QtWidgets.QLabel(self.WelcomeFrame_3)
                self.label_8.setGeometry(QtCore.QRect(90, 10, 31, 31))
                self.label_8.setStyleSheet("font: 14pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color: #7f7f7f")
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.WelcomeFrame_3)
                self.label_9.setGeometry(QtCore.QRect(90, 40, 51, 41))
                self.label_9.setStyleSheet("font: 24pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color:#323232")
                self.label_9.setObjectName("label_9")
                self.WelcomeFrame_4 = QtWidgets.QFrame(self.centralwidget)
                self.WelcomeFrame_4.setGeometry(QtCore.QRect(210, 0, 1061, 51))
                self.WelcomeFrame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.WelcomeFrame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.WelcomeFrame_4.setFrameShadow(QtWidgets.QFrame.Raised)
                self.WelcomeFrame_4.setObjectName("WelcomeFrame_4")
                self.label_10 = QtWidgets.QLabel(self.WelcomeFrame_4)
                self.label_10.setGeometry(QtCore.QRect(820, 10, 231, 31))
                self.label_10.setStyleSheet("font: 18pt \".AppleSystemUIFont\"; \n"
        "background-color: rgb(255, 255, 255);\n"
        "color: #7f7f7f")
                self.label_10.setObjectName("label_10")
                self.WelcomeFrame_5 = QtWidgets.QFrame(self.centralwidget)
                self.WelcomeFrame_5.setGeometry(QtCore.QRect(10, 0, 201, 91))
                self.WelcomeFrame_5.setStyleSheet("background-color: rgba(106, 108, 108, 157); color: white;\n"
        "")
                self.WelcomeFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.WelcomeFrame_5.setFrameShadow(QtWidgets.QFrame.Raised)
                self.WelcomeFrame_5.setObjectName("WelcomeFrame_5")
                self.label_13 = QtWidgets.QLabel(self.WelcomeFrame_5)
                self.label_13.setGeometry(QtCore.QRect(70, 10, 51, 31))
                self.label_13.setStyleSheet("")
                self.label_13.setObjectName("label_13")
                self.label_14 = QtWidgets.QLabel(self.WelcomeFrame_5)
                self.label_14.setGeometry(QtCore.QRect(60, 40, 71, 31))
                self.label_14.setStyleSheet("font: 13pt \".AppleSystemUIFont\";")
                self.label_14.setObjectName("label_14")
                self.startButton.raise_()
                self.stopButton.raise_()
                self.changeExerciseButton.raise_()
                self.ExportDataButton.raise_()
                self.SideColum.raise_()
                self.overviewSide.raise_()
                self.historySide.raise_()
                self.goalSide.raise_()
                self.patientSetup.raise_()
                self.Logout.raise_()
                self.changePatient.raise_()
                self.WelcomeFrame.raise_()
                self.WelcomeFrame_2.raise_()
                self.WelcomeFrame_3.raise_()
                self.WelcomeFrame_4.raise_()
                self.label_5.raise_()
                self.WelcomeFrame_5.raise_()
                OverViewWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(OverViewWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
                self.menubar.setObjectName("menubar")
                OverViewWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(OverViewWindow)
                self.statusbar.setObjectName("statusbar")
                OverViewWindow.setStatusBar(self.statusbar)

                self.retranslateUi(OverViewWindow)
                QtCore.QMetaObject.connectSlotsByName(OverViewWindow)

        def retranslateUi(self, OverViewWindow):
                _translate = QtCore.QCoreApplication.translate
                OverViewWindow.setWindowTitle(_translate("OverViewWindow", "OverViewWindow"))
                self.startButton.setText(_translate("OverViewWindow", "Start"))
                self.stopButton.setText(_translate("OverViewWindow", "Stop"))
                self.changeExerciseButton.setText(_translate("OverViewWindow", "Change Exercise"))
                self.ExportDataButton.setText(_translate("OverViewWindow", "Export Data"))
                self.overviewSide.setText(_translate("OverViewWindow", "Overview"))
                self.historySide.setText(_translate("OverViewWindow", "History"))
                self.goalSide.setText(_translate("OverViewWindow", "Goal"))
                self.patientSetup.setText(_translate("OverViewWindow", "Patient Setup"))
                self.Logout.setText(_translate("OverViewWindow", "Logout"))
                self.changePatient.setText(_translate("OverViewWindow", "Change Patient"))
                self.label_3.setText(_translate("OverViewWindow", "ACTIVITY"))
                self.label_4.setText(_translate("OverViewWindow", "Wrist Extension"))
                self.label_5.setText(_translate("OverViewWindow", "Session no. "))
                self.label_6.setText(_translate("OverViewWindow", "MVC"))
                self.label_7.setText(_translate("OverViewWindow", "---.--mV"))
                self.label_8.setText(_translate("OverViewWindow", "REP"))
                self.label_9.setText(_translate("OverViewWindow", "-/3"))
                self.label_10.setText(_translate("OverViewWindow", "Paitent: Jone Swith"))
                self.label_13.setText(_translate("OverViewWindow", "Clinician"))
                self.label_14.setText(_translate("OverViewWindow", "Pippa Pepo"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     OverViewWindow = QtWidgets.QMainWindow()
#     ui = Ui_OverviewWindow()
#     ui.setupUi(OverViewWindow)
#     OverViewWindow.show()
#     sys.exit(app.exec_())
